### ISSUE TITLE
Support metrics from the beginning

### ISSUE THREAD

**Issue by Airblader** [ververica/ververica-platform-playground#17]
Currently once a user is essentially done with the tutorial and has a working playground, they are told that in order to support metrics they need to tear it down again and re-run the setup with a `--with-metrics`.

Either one of these alternatives would make for a smoother experience in my opinion:

1. Just enable it by default. IMO we need to do it like this unless there is a really good reason not to.
2. Mention the flag in the setup step already.

**Comment by knaufk** [comment]
With the latest changes you can run "--with-metrics" and "--with-logging" without tearing down the existing environment.
