### ISSUE TITLE
Set URL for the guide to the repository

### ISSUE THREAD

**Issue by Airblader** [ververica/ververica-platform-playground#18]
On GitHub repositories you can set a URL which will be shown next to the description here:

![screenshot-2020-04-01_12-07-52](https://user-images.githubusercontent.com/2392216/78125548-7a19d200-7411-11ea-934c-4ce76f41d03f.png)

I think we should provide the URL to the getting started guide. This is a more accessible place than the README (where it should also be linked, of course) as no scrolling down or parsing text is required and users just sort of expect the most relevant link to be there.

**Comment by knaufk** [comment]
Thanks. Done. Please have a look and check if that's what you had in mind.

**Comment by Airblader** [comment]
It is, thanks!
