### ISSUE TITLE
Mention the example Jar URI earlier

### ISSUE THREAD

**Issue by Airblader** [ververica/ververica-platform-playground#19]
As I was going through the getting started guide when creating the deployment I needed to enter the Jar URI. In the screenshot I saw a long, non-copyable URL and I felt lost at whether I should copy it or what I would have to provide. Only after a little bit I noticed the info box which is way below.

I think there are two improvements to be made:

1. The list with explanations for each required input (name, deployment target, …) should come before the screenshot.
2. This description for Jar URI should already mention the example URI.

**Comment by knaufk** [comment]
Thank you. Done. Change will go live with the next release.
