### ISSUE TITLE
How to drain a job

### ISSUE THREAD

**Issue by cyrilou242** [ververica/ververica-platform-playground#20]
Hello, great project thanks for sharing ! My company currently uses GCP dataflow, we're considering  migrating to another platform. Demo in local is working fine. I'm very new to flink so I may have missed some basic stuff.
I see it is possible in flink to drain with `flink stop --drain`.

Is it be possible to perform a pipeline "drain" operation in the ververica system? 

I see there their is the state CANCELED for a Deployment but it's not clear to me if it would stop with or without draining. 

For flink job, I see the upgrade strategy can be stateless or stateful. 
In my case, I would like to have a flink job being stateful, for instance to easily update the parallelism.
Then when doing a change that will make the new job not compatible with the current checkpoints, I would like to drain the current running flink job, and perform a new deployment.

**Comment by knaufk** [comment]
Hi @cyrilou242, 

thanks for opening this ticket and trying out Ververica Platform. 

"Draining" is currently possible by setting the following annotation on your Deployment. 

```
metadata:
  annotations:
    com.dataartisans.appmanager.controller.deployment.stop-with-drain: 'true'
```

This feature is currently undocumented and will finds it way into a proper Upgrade Strategy soon. 

In your case, you would set/unset this annotation before performing an upgrade depending on the desired behavior.

Hope this helps and looking forward to more feedback, 

Konstantin

**Comment by cyrilou242** [comment]
Thanks a lot I'll have a try!
