### ISSUE TITLE
Artifact section missing in the UI for the playground 2.1 branch

### ISSUE THREAD

**Issue by danp11** [ververica/ververica-platform-playground#31]
Hi, 

I have followed https://www.ververica.com/blog/analyzing-github-activity-with-ververica-platform-community-edition but when I open the Ververica platform UI the "Artifacts" sections isn't displayed.

Could it be that the blob storage hasn't been registered properly?

Im on windows with minikube and all the pods starts correctly.

Any advice would be appreciated. 

Thanks,

Regards
Dan

**Comment by knaufk** [comment]
Hi Dan, 

thank you for trying out Ververica Platform CE. Did you change any of the values files before installation, or did you simply run `setup.sh`?


Could you send me the content of http://<ververica-platform>/ui/config.json as well as the output of `kubectl -n vvp get configmaps vvp-ververica-platform-config -o yaml`?

Cheers, 

Konstantin

**Comment by danp11** [comment]
Hi and thanks for your reply. Ive removed minikube and installed everything again but still experience this problem.

http:///ui/config.json doesnt work and below is the output from the kubectl.

Thanks again, 

/Dan

PS C:\Windows\system32> kubectl -n vvp get configmaps vvp-ververica-platform-config -o yaml
apiVersion: v1
data:
  application-prod-user.yaml: |
    spring:
      datasource:
        url: jdbc:sqlite:/vvp/data/vvp.db?journal_mode=WAL&synchronous=FULL&busy_timeout=10000
    vvp:
      appmanager:
        cluster:
          kubernetes.artifact-fetcher.image-registry: registry.ververica.com/v2.1
          kubernetes.artifact-fetcher.image-repository: vvp-artifact-fetcher
          kubernetes.artifact-fetcher.image-tag: 2.1.1
      auth:
        enabled: false
      blobStorage:
        baseUri: s3://vvp
        s3:
          endpoint: http://minio.vvp.svc:9000
      flinkDeploymentDefaults:
        registry: registry.ververica.com/v2.1
        repository: flink
      globalDeploymentDefaults: |
        spec:
          state: RUNNING
          template:
            spec:
              resources:
                jobmanager:
                  cpu: 0.5
                  memory: 1G
                taskmanager:
                  cpu: 0.5
                  memory: 1G
              flinkConfiguration:
                state.backend: filesystem
                taskmanager.memory.managed.fraction: 0.0 # no managed memory needed for filesystem statebackend
                high-availability: vvp-kubernetes
                metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
              kubernetes:
                pods:
                  annotations:
                    prometheus.io/port: '9249'
                    prometheus.io/scrape: 'true'
      license:
        acceptCommunityEditionLicense: true
      persistence:
        type: local
      platformKubernetesNamespace: vvp
      registry: registry.ververica.com/v2.1
      ui:
        linkTemplates:
          metrics: http://localhost:3000/d/77Nra5XZz/flink-dashboard?var-deploymentId=<%=
            deploymentId %>
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: vvp
    meta.helm.sh/release-namespace: vvp
  creationTimestamp: "2020-07-04T12:58:25Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: ververica-platform-4.1.1
    component: ververica-platform
    heritage: Helm
    release: vvp
    system: ververica-platform
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:application-prod-user.yaml: {}
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:component: {}
          f:heritage: {}
          f:release: {}
          f:system: {}
    manager: Go-http-client
    operation: Update
    time: "2020-07-04T12:58:25Z"
  name: vvp-ververica-platform-config
  namespace: vvp
  resourceVersion: "816"
  selfLink: /api/v1/namespaces/vvp/configmaps/vvp-ververica-platform-config
  uid: c5459f9d-fee8-4ae3-86eb-7db88ad44f41

**Comment by knaufk** [comment]
Sorry for the late reply. Github swallowed part of the URL there. I meant `http://<vvp-host>:<port>/ui/config.json`. The configuration looks good otherwise.

**Comment by danp11** [comment]
No worries! Here is the output from ui:

{"version":"2.1","server":{"endpoint":"/api/v1"},"platformKubernetesNamespace":"vvp","refreshMs":5000,"messageHideMs":3000,"dateFormat":"YYYY-MM-DD, HH:mm:ss","linkTemplates":{"flinkUi":"/flink-ui/v1/<%= namespace %>/jobs/<%= jobId %>/","metrics":"http://localhost:3000/d/77Nra5XZz/flink-dashboard?var-deploymentId=<%= deploymentId %>"},"licenseInformation":{"licensedTo":null,"isCommunityEdition":true,"expiresOn":null,"cpuQuotaType":"UNLIMITED","cpuQuota":null,"isTrial":null,"isNotForResale":null},"flinkVersions":["1.8","1.9","1.10"],"flinkImageTags":["1.10.0-stream1-scala_2.12","1.10.1-stream1-scala_2.12","1.8.2-stream1-scala_2.11","1.8.3-stream3-scala_2.11","1.9.0-stream1-scala_2.11","1.9.0-stream1-scala_2.12","1.9.1-stream2-scala_2.12","1.9.2-stream2-scala_2.12","1.9.3-stream1-scala_2.12"],"components":{"artifacts":{"enabled":true},"blobStorage":{"baseUri":"s3://vvp"},"logging":{"enabled":false},"metrics":{"enabled":true},"sql":{"enabled":false}},"extraConfig":null}

**Comment by danp11** [comment]
![vvp](https://user-images.githubusercontent.com/6255904/86967141-888f2c80-c16a-11ea-8ce9-7da2d48df8e5.png)

**Comment by knaufk** [comment]
Ok, it seems that the side bar does not behave well with your screen resolution. If you scroll in the small section of the navigation bar that is scrollable, you should be able to find the "Artifacts" entry. We will improve the side bar in our upcoming release.

**Comment by danp11** [comment]
Ok thanks. Now I found the scrollbar also so I can continue with the series :-)

**Comment by knaufk** [comment]
Great. Let us know if you run into problems.
