### ISSUE TITLE
How to work with kerberos with ververica hosted flink image ?

### ISSUE THREAD

**Issue by anshulbansal2** [ververica/ververica-platform-playground#33]
How can we do something like this : security.kerberos.login.keytab: 's3://vvp/artifacts/namespaces/default/coremojo.keytab'

**Comment by knaufk** [comment]
Support for HDFS 2/3 (including Kerberos) will be added in our upcoming release in the coming weeks. We expect the keytab to be stored in a Kubernetes Secret. Would this work for you?

**Comment by anshulbansal2** [comment]
Could you please give an example, where to add it?

**Comment by knaufk** [comment]
There will be an example in the documentation that come with the next release. The configuration via a Kubernetes Secret will work along the lines of 

```
kubectl create secret generic my-blob-storage-credentials \
  --from-file hdfs.core-site.xml=core-site.xml \
  --from-file hdfs.hdfs-site.xml=hdfs-site.xml \
  --from-file hdfs.krb5.conf=krb5.conf \
  --from-file hdfs.keytab=keytab \
  --from-file hdfs.keytab-principal=keytab-principal
```

This secret is then referenced in the Ververica Platform values.yaml.

**Comment by anshulbansal2** [comment]
Thanks  @knaufk , Is there any suggested work around for now ?

**Comment by knaufk** [comment]
This has been released in the latest release of Ververica Platform. Please see [1] for the corresponding documentation. 

[1] https://docs.ververica.com/administration/blob_storage.html#example-apache-hadoop-hdfs
