### ISSUE TITLE
I think vvp couldn't access from local area network by default, how can I resolve it? 

### ISSUE THREAD

**Issue by MarcelLeon** [ververica/ververica-platform-playground#46]
I follow the document step-by-step( minikube helm vvp etc. ), https://docs.ververica.com/getting_started/installation.html#setting-up-the-playground
then I start vvp, and it's work. like...

```
[hadoop@hosts101-230 ververica-platform-playground]$ kubectl port-forward service/vvp-ververica-platform 8080:80

Forwarding from 127.0.0.1:8080 -> 8080

Forwarding from [::1]:8080 -> 8080

Handling connection for 8080
```
the port status show:
![image](https://user-images.githubusercontent.com/17470121/109190023-9f54c300-77cf-11eb-9361-49ef79cebf11.png)

**but it couldn't visit from local area network. I try to curl command locally**
```
# it's work
curl http://localhost:8080/api/v1/namespaces/defaults/deployments -H "Accept: application/yaml"
```
![image](https://user-images.githubusercontent.com/17470121/109193103-fc9e4380-77d2-11eb-81e5-f015013244c6.png)

```
# doesn't work
curl http://192.168.101.230:8080/api/v1/namespaces/defaults/deployments -H "Accept: application/yaml"
```
![image](https://user-images.githubusercontent.com/17470121/109192256-f491d400-77d1-11eb-846f-7827ce7de8a1.png)

how can I resolve it?   thx

**Comment by knaufk** [comment]
`minikube` and `kubectl port-forward` are both meant to be used for local development and experimentation. To expose Ververica Platform to the outside, I suggest, to use an Ingress (or possible a Service of type NodePort). If you would like to stick to minikube for the time being, it might then be easier to use the "None" driver [1], which runs Kubernetes directly on your machine instead of a VM or docker. 

[1] https://minikube.sigs.k8s.io/docs/drivers/none/

**Comment by MarcelLeon** [comment]
> `minikube` and `kubectl port-forward` are both meant to be used for local development and experimentation. To expose Ververica Platform to the outside, I suggest, to use an Ingress (or possible a Service of type NodePort). If you would like to stick to minikube for the time being, it might then be easier to use the "None" driver [1], which runs Kubernetes directly on your machine instead of a VM or docker.
> 
> [1] https://minikube.sigs.k8s.io/docs/drivers/none/

Thanks for your reply, I try to execute
```kubectl port-forward service/vvp-ververica-platform --address 192.168.101.230 8080:80```
it works now... this "sql-platform" is so cool!

**Comment by knaufk** [comment]
Glad it works now.

**Comment by MarcelLeon** [comment]
> > `minikube` and `kubectl port-forward` are both meant to be used for local development and experimentation. To expose Ververica Platform to the outside, I suggest, to use an Ingress (or possible a Service of type NodePort). If you would like to stick to minikube for the time being, it might then be easier to use the "None" driver [1], which runs Kubernetes directly on your machine instead of a VM or docker.
> > [1] https://minikube.sigs.k8s.io/docs/drivers/none/
> 
> Thanks for your reply, I try to execute
> `kubectl port-forward service/vvp-ververica-platform --address 192.168.101.230 8080:80`
> it works now... this "sql-platform" is so cool!

For note this, I had written a Chinese installed reference.
https://marcelleon.github.io/2021/02/26/vvp-install-note/
